[package]
name = "libscsi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.25.0"
bitflags = "1.3.2"
modular-bitfield-msb = "0.11.2"